name: notes_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.6
  package_info: ^2.0.0
  universal_io: ^2.0.4
  device_info: ^2.0.0
  provider: ^5.0.0
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  firebase_storage: ^8.1.0
  firebase_analytics: ^8.2.0
  firebase_messaging: ^10.0.0
  firebase_crashlytics: ^2.0.4
  cloud_firestore: ^2.2.0
  image_picker: ^0.7.4
  cached_network_image: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shimmer: ^2.0.0
  mime: ^1.0.0
  crop: ^0.5.0
  flutter_spinkit: ^5.0.0
  flutter_easyloading: ^3.0.0
  overlay_support: ^1.2.1
  transparent_image: ^2.0.0
  url_launcher: ^6.0.3
  flutter_colorpicker: ^0.4.0
  google_fonts: ^2.1.0
  logging: ^1.0.1
  avatar_glow: ^2.0.1
  material_design_icons_flutter: ^5.0.5955-rc.1
  eva_icons_flutter: ^3.0.0
  permission_handler: ^8.0.0+2
  auto_route: ^2.3.0
  responsive_builder: ^0.4.1
  #auto_route_generator: ^2.1.0
  feather_icons: ^1.1.0-nullsafety.0
  dots_indicator: ^2.0.0
  animated_text_kit: ^4.2.1
  visibility_detector: ^0.2.0
  flutter_staggered_grid_view: ^0.4.0
  layout: ^0.6.2
  uuid: ^3.0.4
  flutter_reorderable_list: ^1.0.0
  share: ^2.0.4
  date_time_picker: ^2.1.0
  collection: ^1.15.0-nullsafety.4
  flutter_tts: ^3.2.2
  font_awesome_flutter: ^9.1.0
  flutter_datetime_picker: ^1.5.1
  websafe_svg: ^2.0.0
  flutter_svg: ^0.21.0+1
  deep_pick: ^0.8.0
  carousel_slider: ^4.0.0
  timeago: ^3.0.2
  intl: ^0.17.0
  tab_indicator_styler: ^2.0.0-null-safety


dev_dependencies:
  flutter_lints: ^1.0.0

  auto_route_generator: ^2.1.0
  build_runner: ^2.0.6
  change_app_package_name: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/book.json
    - assets/Icons/
    - assets/images/
    - assets/LICENSE

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Flaunters
      fonts:
        - asset: fonts/Flaunters.otf
          style: italic
    - family: GresaRegular
      fonts:
        - asset: fonts/GresaRegular.ttf
          style: italic
    - family: YTSans
      fonts:
        - asset: assets/fonts/youtube-sans-medium.ttf
          weight: 500
        - asset: assets/fonts/youtube-sans-light.ttf
          weight: 300
        - asset: assets/fonts/youtube-sans-bold.ttf
          weight: 700
    - family: Product Sans
      fonts:
        - asset: assets/fonts/productSans/bold.ttf
          weight: 700
        - asset: assets/fonts/productSans/regular.ttf
          weight: 400
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
    - family: LaiSiangtho
      fonts:
        - asset: assets/fonts/LaiSiangtho.ttf
    - family: Mm3Web
      fonts:
        - asset: assets/fonts/Mm3Web.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
